### ISSUE TITLE
When scanning crashes

### ISSUE THREAD

**Issue by mrkaban** [VISWESWARAN1998/Mrida#3]
Found your program [here](https://www.codeproject.com/Articles/5162378/Antivirus-Part-2)

When updating a lot of such errors, I attach a screenshot.

when you try to start a scan, the program simply closes.

Windows 10 x64

**Comment by mrkaban** [comment]
![Снимок](https://user-images.githubusercontent.com/14289360/72812578-565d4180-3c94-11ea-8fb9-a3aed1c4bc83.jpg)

**Comment by VISWESWARAN1998** [comment]
Mrida has been programmed as a server client model, so you need to start the server by running

`mrida.exe` and then run the gui wrapper. You won't see the error on updating.

**Comment by mrkaban** [comment]
Thanks, really. Now I’ll update it again, and try it on old viruses. Very common in 2011 and 2012.

And can you add the "about" section in the program and indicate there the license under which you distribute the program. For organizations, this is critical.

**Comment by mrkaban** [comment]
checked on 15 old viruses, and not a single one was detected. I attach the scan log to Kaspersky Anti-Virus of the same folder. The name of the threat is indicated there.
[2.txt](https://github.com/VISWESWARAN1998/Mrida/files/4091929/2.txt)

**Comment by VISWESWARAN1998** [comment]
I have not covered all the threats to detect, however I have explained about adding signatures to the antivirus. 

Meanwhile you can test this software with ransomware  like wanna-cry and other common threats which I have added for testing.
